import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import { Theme } from "@radix-ui/themes";
import "./globals.css";

const inter = Inter({
  subsets: ['latin'], // Load specific character subsets
  variable: '--font-inter', // Add as a CSS variable (optional)
  display: 'swap',         // Use swap for better loading performance
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
              <Theme>
              {children}
              </Theme>
      </body>
    </html>
  );
}
