import Navbar from "./components/navbar";
import type { Metadata } from "next";
import { IBM_Plex_Sans, Inter } from 'next/font/google';
import { Theme } from "@radix-ui/themes";
import "./globals.css";

const sans = IBM_Plex_Sans({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-ibm-plex-sans'
})

const inter = Inter({
  subsets: ['latin'], // Load specific character subsets
  variable: '--font-inter', // Add as a CSS variable (optional)
  display: 'swap',         // Use swap for better loading performance
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`gradient ${inter.variable} ${sans.variable} antialiased`}
      >
              <Theme hasBackground={false}>
              <Navbar />
              {children}
              </Theme>
      </body>
    </html>
  );
}
